package:
  name: root
  version: !!str 5.34.26

source:
  fn: root_v5.34.26.source.tar.gz
  url: http://root.cern.ch/download/root_v5.34.26.source.tar.gz

requirements:
  build:
    - python
    - gsl

  run:
    - python
    - gsl

build:
  number: 0

  has_prefix_files:
    - lib/cint/cint/lib/G__c_ipc.d
    - lib/cint/cint/lib/G__c_posix.d
    - lib/cint/cint/lib/G__c_stdfunc.d

  binary_has_prefix_files:
    - lib/libASImage.so
    - lib/libCint.so
    - lib/libCore.so
    - lib/libEG.so
    - lib/libGeom.so
    - lib/libGpad.so
    - lib/libGraf.so
    - lib/libGui.so
    - lib/libHtml.so
    - lib/libNet.so
    - lib/libProofBench.so
    - lib/libProof.so
    - lib/libRGL.so
    - lib/libRint.so
    - lib/libRIO.so
    - lib/libRootAuth.so
    - lib/libTreeViewer.so

test:
  # Python imports
  imports:
    - ROOT

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - root-config --version

about:
  home: http://root.cern.ch
  license: LGPLv2
  summary: "Analysis package for particle physics"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
