package:
  name: root_numpy
  version: !!str 3.3.1

source:
  fn: root_numpy-3.3.1.tar.gz
  url: https://pypi.python.org/packages/source/r/root_numpy/root_numpy-3.3.1.tar.gz
  md5: c071f232f6249d8b58f41a5925b9cc6e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - root_numpy = root_numpy:main
    #
    # Would create an entry point called root_numpy that calls root_numpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - root

test:
  # Python imports
  imports:
    - root_numpy

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://rootpy.github.io/root_numpy
  license:  MIT License
  summary: 'An interface between ROOT and NumPy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
